// <auto-generated />
using HotelApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelApi.Migrations
{
    [DbContext(typeof(ConnectionDbContext))]
    [Migration("20221202230745_SubindoBanco")]
    partial class SubindoBanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HotelApi.Model.HotelPessoaJuridica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EnderecoHotel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeHotel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuantidadeQuartos")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("HotelPessoaJuridica");
                });

            modelBuilder.Entity("HotelApi.Model.Quarto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("HotelPessoaJuridicaId")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeQuarto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroQuarto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelPessoaJuridicaId");

                    b.ToTable("Quarto");
                });

            modelBuilder.Entity("HotelApi.Model.Quarto", b =>
                {
                    b.HasOne("HotelApi.Model.HotelPessoaJuridica", "HotelPessoaJuridica")
                        .WithMany("Quartos")
                        .HasForeignKey("HotelPessoaJuridicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HotelPessoaJuridica");
                });

            modelBuilder.Entity("HotelApi.Model.HotelPessoaJuridica", b =>
                {
                    b.Navigation("Quartos");
                });
#pragma warning restore 612, 618
        }
    }
}
